name: Code quality

on:
  push:
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: "npm"
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Install dependencies
        run: npm ci
      - name: Build package
        run: npm run build
      - name: Run format and lint
        run: npm run format && npm run lint
      - name: Run `svelte-check`
        run: npx svelte-check --output human
